### ISSUE TITLE
Not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by Aliallameh** [sinadarvi/windows-persian-keyboard-for-linux#11]
I can confirm that both Automatic and manual ways will not work anymore.
it will add the option in the layout setting, and you can add it, but it will not work as switching to this language is not working.

**Comment by tsalehm** [comment]
@rez4mt 

HI. It's ok and it works on ubuntu 22 very well

> it will add the option in the layout setting, and you can add it, but it will not work as switching to this language is not working.

when you add the files (you'd better use curl) you have to remove all Persian layouts from the settings and then, add this one

@sinadarvi 
I think It's because it has the same name as the old layout of ubuntu when we add it 
and its name shouldn't be 'ir'. it should be something like 'ir-win'

**Comment by sinadarvi** [comment]
@tsalehm interesting, 
I had no issue with Ubuntu 22, I will check some more and if the issue happened, I will consider your solution for the test.

**Comment by sinadarvi** [comment]
@Aliallameh could you please also check and test this as well? if changing 'ir' to 'ir-win' works, I could change it in repo. thanks.

**Comment by tsalehm** [comment]
@sinadarvi 
>if changing 'ir' to 'ir-win' works, I could change it in repo.

when we add a new layout with the name 'ir', ubuntu settings will look for the old layout in the new file 'ir'
so it somehow screws the layouts. **new setting files shouldn't have the same name as the old ones**

when we remove Persian layouts and add them again, we're actually reloading layouts

**Comment by sinadarvi** [comment]
The issue has been solved with a new PR. if you did have other problem, feel free to reopen this issue. thank you all.

**Comment by hamed-ahangari** [comment]
Hi. It sill doesn't work on Ubuntu 22.04. With this keyboard layout selected, I only can write English.
Also, when I click on "View Keyboard Layout" in the keyboard settings, Ubuntu encounters an error and wants to send reports.
Specs: Ubuntu 22.04.1 LTS, 64-bit, GNOME Version 42.5.
Thanks.

**Comment by sinadarvi** [comment]
could you please try again with new changes?

**Comment by sinadarvi** [comment]
@MasterKia  I don't have access to a Linux system for a while, could you make a pull request with new changes?

**Comment by tsalehm** [comment]
@sinadarvi PR #15 will fix this bug
PLEASE DON'T merge any other PR related to this bug. because they will cause another bug

**Comment by tsalehm** [comment]
@sinadarvi yo!?

**Comment by sinadarvi** [comment]
@tsalehm have been merged. thanks for your contribution. 🙏
