### ISSUE TITLE
Merge this layout in the upstream xkeyboard project

### ISSUE THREAD

**Issue by MasterKia** [sinadarvi/windows-persian-keyboard-for-linux#16]
The upstream project for all keyboard layouts is the `xkeyboard` project.

If they agree to merge the "Windows Persian layout" then it'll be released, picked up by all GNU/Linux distributions soon after and then be available to everyone as the change trickles down to all users.

I created an issue about that on their repo two weeks ago:
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/367

The response:

> The repo you are linking to does not provide any license information, so we cannot just grab and include that layout.  You will need to get the author of that layout to post a merge request here.

Could you add a LICENSE file to this repo so that they could include the layout by themselves? Otherwise you'd have to make a merge request by yourself.

> Also, can you confirm that the layout on the linked github site is the same as [what Windows has](https://kbdlayout.info/kbdfa)?
And that GNU/Linux has [this one](https://kbdlayout.info/kbdfar)?  (I cannot read Persian, so for me it's nearly impossible to compare.)

I compared the standard Windows Persian layout to your layout, the only difference is in the `Shift+G` key; It should return `ۀ` but it returns `ة` instead.

There's an already open pull request by @cs127 to fix the above issue:
https://github.com/sinadarvi/windows-persian-keyboard-for-linux/pull/9

Could you merge the PR?

**Comment by sinadarvi** [comment]
First, thank you for your effort. I understand the issues. I will provide a license in this repo and I will ask @cs127 to check with the newer version. but the big problem here is that I don't have a Linux system anymore and because of my workflow and my schedule, I'm not able to install one some people telling me this repo not working on their system (https://github.com/sinadarvi/windows-persian-keyboard-for-linux/issues/13) and I can't verify it my self.

**Comment by cs127** [comment]
> I will ask @cs127 to check with the newer version.

I just updated my PR to the latest version a few minutes ago!

**Comment by sinadarvi** [comment]
@cs127 
oh, so you may didn't see my comment (https://github.com/sinadarvi/windows-persian-keyboard-for-linux/pull/9#issuecomment-1460070005(

**Comment by cs127** [comment]
> @cs127 oh, so you may didn't see my comment ([#9 (comment)](https://github.com/sinadarvi/windows-persian-keyboard-for-linux/pull/9#issuecomment-1460070005)

I saw your comment now. Yes, as I already said in this thread, I updated the PR today, and it matches with the latest version now.

**Comment by cs127** [comment]
> @cs127 I think it was proposed with a PR. we have done it because of distinguishing the difference between `ir` and `ir_win` by separating them as their own independent files. if you still think previously was better, I would be happy to hear your opinion and reason.

Other languages in xkb which have a Windows layout (Spanish, Italian, Finnish, and Ukranian just to name a few) do so by having the Windows layout as a `winkeys` variant in the same symbols file as the main layout (`es`, `it`, `fi`, and `ua` respectively). At least in my opinion, doing the same for `ir` makes a lot more sense, instead of having a separate `ir_win` file.

> I think we could just ask the `xkeyboard` project for help and figure out whether it needs to be `ir` or `ir_win`, etc.

Sure, we can do that too.

**Comment by sinadarvi** [comment]
I have checked the issue. I have added a License and Merged the PR. but if you don't mind guys, please make the changes to the `ir` file and test it.

**Comment by cs127** [comment]
I'm currently making my own modified `ir` file to send as a PR to the xkb project. Let me know what you think.

**Comment by cs127** [comment]
I made the PR: [!471](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/471).

Thank you guys for the help. It's only a matter of time until the Persian Windows layout becomes a part of xkb! :)

**Comment by sinadarvi** [comment]
it was a good experience. thank you, guys. I will close this issue.

**Comment by MasterKia** [comment]
:tada: It got merged! Finally we can use the Windows layout by default on our GNU/Linux systems.

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/367#note_e7813356297bd38961a59ada4fa67cc2f8146b08

All thanks to @cs127 for going through with the merge request.

**Comment by cs127** [comment]
:tada: thank you guys, it was fun!
But we will have to wait for the next release of xkeyboard-config (2.39), which will be released in about 3 months, according to their release schedule :)
